version: 1
formatters:
  simple:
    format: '%(asctime)s  %(levelname)-8s %(message)s'
  network:
    format: '%(asctime)s  %(levelname)-8s %(address)-21s %(method)-6s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: /var/log/proxypool/pool.log
    maxBytes: 5120000
    backupCount: 5
  server:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: network
    filename: /var/log/proxypool/server.log
    maxBytes: 5120000
    backupCount: 10
loggers:
  console_logger:
    level: DEBUG
    handlers: [console]
    propagate: no
  file_logger:
    level: DEBUG
    handlers: [file]
    propagate: no
  server_logger:
    level: DEBUG
    handlers: [server]
    propagate: no
root:
  level: DEBUG
  handlers: [file]
